mongodb:
  enabled: true
  image:
    registry: docker.io
    repository: mongo
    tag: "6.0"
  persistence:
    enabled: true
    storageClass: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    mountPath: /data/db
  updateStrategy:
    type: Recreate
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
populate:
  enabled: false
  initCommands:
    - open5gs-dbctl create_admin admin 1423
    - open5gs-dbctl add_ue_with_apn 001010123456789 00112233445566778899AABBCCDDEEFF 000102030405060708090A0B0C0D0E0F internet
mme:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false
hss:
  enabled: false
pcrf:
  enabled: false
webui:
  enabled: false
nrf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
scp:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
amf:
  enabled: true
  hostNetwork: true
  updateStrategy:
    type: Recreate
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    guamiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        s_nssai:
          - sst: 1
          - sst: 1
            sd: "000000"
    networkName: Gradiant
smf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  config:
    use_mongodb_subscriber: true
    freeDiameter: false
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
upf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
ausf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  image:
    registry: ghcr.io
    repository: nss-networks/open5gs
    tag: xor-patch
    pullPolicy: IfNotPresent
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
udm:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  image:
    registry: ghcr.io
    repository: nss-networks/open5gs
    tag: xor-patch
    pullPolicy: IfNotPresent
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
udr:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  image:
    registry: ghcr.io
    repository: nss-networks/open5gs
    tag: xor-patch
    pullPolicy: IfNotPresent
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
bsf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
nssf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
pcf:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: open5gs-master
  config:
    sbi:
      client:
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
        scp:
          enabled: false
